name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        sudo add-apt-repository -u -y ppa:s-ramacher/ait
        sudo apt-get install librelic-dev pkg-config
        python -m pip install --upgrade pip
        pip install setuptools wheel "Cython >= 0.28" pkgconfig
    - name: Build sdist
      run: |
        python setup.py sdist
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}
